[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    X-DNS-Prefetch-Control = "on"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store, max-age=0"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"

# Redirections pour le SEO
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/accueil"
  to = "/"
  status = 301

[[redirects]]
  from = "/club"
  to = "/"
  status = 301

[[redirects]]
  from = "/parkour"
  to = "/"
  status = 301

# Redirection des anciennes URLs vers les nouvelles
[[redirects]]
  from = "/tshirt"
  to = "/boutique/tshirt"
  status = 301

[[redirects]]
  from = "/inscriptions"
  to = "/inscription"
  status = 301

# Redirection des erreurs 404
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

# Optimisations pour les images
[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Compression et optimisation
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Configuration des fonctions
[functions]
  directory = "netlify/functions"

# Configuration des formulaires
[[redirects]]
  from = "/api/submit-inscription"
  to = "/.netlify/functions/submit-inscription"
  status = 200

[[redirects]]
  from = "/api/submit-contact"
  to = "/.netlify/functions/submit-contact"
  status = 200

# Configuration pour le SEO
[build.environment]
  NODE_ENV = "production"
  NEXT_PUBLIC_SITE_URL = "https://pkba.vertiflow.fr" 