[build]
  command = "npm run build"
  publish = ".next"
  # Add build hook to ensure proper environment variable handling
  [build.environment]
    NODE_VERSION = "18"
    NODE_ENV = "production"
    # Ensure these are available during build
    # NEXT_PUBLIC_SITE_URL
    # NEXT_PUBLIC_SITE_NAME
    # NEXT_PUBLIC_CONTACT_EMAIL
    # NEXT_PUBLIC_CONTACT_PHONE
    # NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
    # NEXT_PUBLIC_EMAILJS_SERVICE_ID
    # NEXT_PUBLIC_EMAILJS_TEMPLATE_ID
    # NEXT_PUBLIC_EMAILJS_PUBLIC_KEY
    # NEXT_PUBLIC_FORMSPREE_CONTACT_FORM_ID
    # NEXT_PUBLIC_FORMSPREE_REGISTRATION_FORM_ID
    # NEXT_PUBLIC_FORMSPREE_ORDER_FORM_ID

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    X-DNS-Prefetch-Control = "on"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store, max-age=0"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"

# Redirections pour le SEO
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/accueil"
  to = "/"
  status = 301

[[redirects]]
  from = "/club"
  to = "/"
  status = 301

[[redirects]]
  from = "/parkour"
  to = "/"
  status = 301

# Redirection des anciennes URLs vers les nouvelles
[[redirects]]
  from = "/tshirt"
  to = "/boutique/tshirt"
  status = 301

[[redirects]]
  from = "/inscriptions"
  to = "/inscription"
  status = 301

# Redirection des erreurs 404
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

# Optimisations pour les images
[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Compression et optimisation
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Configuration des fonctions
[functions]
  directory = "netlify/functions"

# Configuration des formulaires
[[redirects]]
  from = "/api/submit-inscription"
  to = "/.netlify/functions/submit-inscription"
  status = 200

[[redirects]]
  from = "/api/submit-contact"
  to = "/.netlify/functions/submit-contact"
  status = 200

# Configuration des hooks de build
[build.hooks]
  pre_build = "echo 'Starting build with environment variables configured'"
  post_build = "echo 'Build completed successfully'"

# Configuration des variables d'environnement pour le build
[build.environment]
  # Ajouter des variables pour éviter les faux positifs
  SECRETS_SCAN_ENABLED = "true"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_SITE_URL,NEXT_PUBLIC_SITE_NAME,NEXT_PUBLIC_CONTACT_EMAIL,NEXT_PUBLIC_CONTACT_PHONE,NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY,NEXT_PUBLIC_EMAILJS_SERVICE_ID,NEXT_PUBLIC_EMAILJS_TEMPLATE_ID,NEXT_PUBLIC_EMAILJS_PUBLIC_KEY,NEXT_PUBLIC_FORMSPREE_CONTACT_FORM_ID,NEXT_PUBLIC_FORMSPREE_REGISTRATION_FORM_ID,NEXT_PUBLIC_FORMSPREE_ORDER_FORM_ID"
  SECRETS_SCAN_OMIT_PATHS = ".next/**,node_modules/**,.netlify/**,**/*.pack,**/*.js,**/*.html,**/*.rsc,**/cache/**,**/webpack/**,**/static/**,**/server/**,**/standalone/**,**/chunks/**,**/blobs/**,**/deploy/**"

# Configuration du scan des secrets
[secrets_scanning]
  enabled = true
  omit_keys = [
    "NEXT_PUBLIC_SITE_URL",
    "NEXT_PUBLIC_SITE_NAME", 
    "NEXT_PUBLIC_CONTACT_EMAIL",
    "NEXT_PUBLIC_CONTACT_PHONE",
    "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY",
    "NEXT_PUBLIC_EMAILJS_SERVICE_ID",
    "NEXT_PUBLIC_EMAILJS_TEMPLATE_ID",
    "NEXT_PUBLIC_EMAILJS_PUBLIC_KEY",
    "NEXT_PUBLIC_FORMSPREE_CONTACT_FORM_ID",
    "NEXT_PUBLIC_FORMSPREE_REGISTRATION_FORM_ID",
    "NEXT_PUBLIC_FORMSPREE_ORDER_FORM_ID"
  ]
  omit_paths = [
    ".next/**",
    "node_modules/**",
    ".netlify/**",
    "**/*.pack",
    "**/*.js",
    "**/*.html",
    "**/*.rsc",
    "**/cache/**",
    "**/webpack/**",
    "**/static/**",
    "**/server/**",
    "**/standalone/**",
    "**/chunks/**",
    "**/blobs/**",
    "**/deploy/**"
  ] 